# Example Config that uses almost all values

alg: DoubleDQN
alg_kwargs:
  tau: 1.0
  target_freq: 1000
  max_grad_norm: 10
  eps_start: 1.0
  eps_end: 0.05
  eps_frac: 0.1
  random_steps: 1000

optim: Adam
optim_kwargs:
  lr: 0.00025

network: DiscreteMLPCritic
network_kwargs:
    hidden_layers: [256, 256]
    act: ["import", "torch.nn", "ReLU"]

env: CartPole-v1

dataset: ReplayBuffer
dataset_kwargs:
  sample_fn: sample_qlearning
  sample_kwargs:
    discount: 0.99
    nstep: 1
    batch_size: 64
  capacity: 500000
  fetch_every: 500

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 500000 # The total number of steps to train
  log_freq: 250 # How often to log values
  profile_freq: 100
  env_freq: 0.25
  eval_freq: 1000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null
