# NOTE: DrQv2 Implementation is UNTESTED!!!!!!!!!!

alg: DRQV2
alg_kwargs:
  tau: 0.01
  critic_freq: 1
  actor_freq: 1
  target_freq: 1
  noise_clip: 0.3
  std_schedule: [1.0, 0.1, 500000]
  init_steps: 4000

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorCriticPolicy
network_kwargs:
  actor_class: DrQv2Actor
  actor_kwargs:
    feature_dim: 50
    hidden_layers: [1024, 1024]
  critic_class: DrQv2Critic
  critic_kwargs:
    feature_dim: 50
    hidden_layers: [1024, 1024]
  encoder_class: DrQv2Encoder

env: CheetahRun-vision-v0

dataset: ReplayBuffer
dataset_kwargs:
  discount: 0.99
  nstep: 3
  capacity: 1000000
  fetch_every: 1000
  batch_size: 256

processor: RandomCrop # Add in the data augmentations!

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 3100000 # The total number of steps to train
  log_freq: 250 # How often to log values
  profile_freq: 200
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 4 # Number of dataloader workers.
