# Example Config that uses almost all values

alg: PPO
alg_kwargs:
  clip_range: 0.2
  clip_range_vf: 0.5
  num_epochs: 10
  normalize_advantage: True
  ent_coeff: 0.0
  vf_coeff: 0.5
  normalize_returns: True
  reward_clip: 10

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorValuePolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [64, 64]
    log_std_bounds: null
    act: ["import", "torch.nn", "Tanh"]
    state_dependent_log_std: False
    squash_normal: False
    log_std_tanh: False
    ortho_init: 1.41421356237
    output_gain: 0.01
  value_class: MLPValue
  value_kwargs:
    hidden_layers: [64, 64]
    act: ["import", "torch.nn", "Tanh"]
    ortho_init: 1.41421356237
    output_gain: 0.01

env: HalfCheetah-v2

dataset: RolloutBuffer
dataset_kwargs:
  discount: 0.99
  gae_lambda: 0.95
  capacity: 2048
  batch_size: 64

processor: RunningObservationNormalizer
processor_kwargs:
  clip: 10
  explicit_update: True

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 1000 # How often to log values
  eval_freq: 10000 # How often to run evals
  profile_freq: 100
  x_axis: env_steps
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null
