# Example Config that uses almost all values

alg: TD3
alg_kwargs:
  tau: 0.005
  policy_noise: 0.1
  target_noise: 0.2
  noise_clip: 0.5
  critic_freq: 1
  actor_freq: 2
  target_freq: 2
  random_steps: 10000

optim: Adam
optim_kwargs:
  lr: 0.001

network: ActorCriticPolicy
network_kwargs:
  actor_class: ContinuousMLPActor
  actor_kwargs:
    hidden_layers: [256, 256]
    output_act: ["import", "torch.nn", "Tanh"]
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256]
    ensemble_size: 2
  ortho_init: true

env: CheetahRun-v0

dataset: ReplayBuffer
dataset_kwargs:
  sample_fn: sample_qlearning
  sample_kwargs:
    discount: 0.99
    nstep: 1
    batch_size: 1
    sample_by_timesteps: False
  capacity: 1000000
  fetch_every: 1000
  distributed: true

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 250 # How often to log values
  profile_freq: 100
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    batch_size: 256
    num_workers: 4 # Number of dataloader workers.
