name: research
channels:
  - pytorch
  - defaults
dependencies:
  - python

  # Development
  - conda-forge::pre-commit

  # pytorch
  - pytorch
  - cpuonly
  - torchvision
  - torchtext
  - torchaudio

  # NP Family
  - numpy
  - scipy
  - scikit-image

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  # For Robosuite (But install robosuite via source)
  - numba

  - pip
  - pip:
      - gym==0.23.1
      - mujoco-py<2.2,>=2.0
      - git+https://github.com/Farama-Foundation/Metaworld.git@master#egg=metaworld
      # The D4RL dependency does not yet support python 3.11 via pip. Instead run this command outside of conda.
      # - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl --ignore-requires-python
