name: research
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python

  # Development
  - conda-forge::pre-commit

  # pytorch
  - pytorch
  - pytorch-cuda=11.7
  - torchvision
  - torchtext
  - torchaudio

  # NP Family
  - numpy
  - scipy
  - scikit-image

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - gym==0.23.1
